const stringToKebab = function (text) {
  return text.toLowerCase().replace(/\W/gm, '-');
};

const FACTION = {
  COMMON: 'Common',
  BROTHERS: 'Battle Brothers',
  HIVES: 'Alien Hives',
  MARAUDERS: 'Orc Marauders',
};

const SEASON = {
  ONE: '1',
}

const TRAITS = {
  CLEAVE: 'Cleave',
};

const upgrade = (name, faction, season, cost, effect = '', weapon, tags) => {
  let finalEffect = effect;
  if (weapon) {
    //finalEffect += ` ${weapon.name}${weapon.traits.length > 0 ? ' - '+weapon.traits : ''} (Rng: ${weapon.range}, Str: ${weapon.strength}, Dmg: ${weapon.damage}) ${weapon.effect}`;
  }
  return {
    key: stringToKebab(name),
    name,
    faction,
    season,
    cost,
    effect: finalEffect,
    weapon,
    tags,
  };
};

const weapon = (name, range, strength, damage, traits, effect) => {
  return {
    key: stringToKebab(name),
    name,
    range,
    strength,
    damage,
    traits,
    effect,
  };
};

const upgradeCards = [
  upgrade(
    'Focused Strike',
    FACTION.COMMON,
    SEASON.ONE,
    10,
    'This model gets +1 strength when using attack actions, but not if it used a charge action.',
    undefined,
    ['attack'],
  ),
  upgrade(
    'Rise to the challenge',
    FACTION.COMMON,
    SEASON.ONE,
    10,
    'If your warband`s hero is killed, this model counts as a hero until the end of the game (may only pick one model to be a hero).',
    undefined,
    ['hero'],
  ),
  upgrade(
    'Kingslayer',
    FACTION.COMMON,
    SEASON.ONE,
    10,
    undefined,
    weapon('Kingslayer',1,2,4,[],'This weapon gets +1 strength and +2 damage against heroes.'),
    ['weapon','melee'],
  ),
  upgrade(
    'Anti-Grav boots',
    FACTION.COMMON,
    SEASON.ONE,
    15,
    'The model gets +1 speed.',
    undefined,
    ['speed'],
  ),
  upgrade(
    'Hit & Run',
    FACTION.COMMON,
    SEASON.ONE,
    15,
    undefined,
    weapon('Hit & Run',1,3,2,[], 'This model may move by 1 hex after using this attack, as long as it doesn`t end up adjecent to the target model.'),
    ['weapon','melee','move'],
  ),
  upgrade(
    'Heroic Confidence',
    FACTION.COMMON,
    SEASON.ONE,
    15,
    'If this model is alive at the end of the game it scores 1 VP. Discard this upgrade if this model is killed at any point.',
    undefined,
    ['vp'],
  ),
  upgrade(
    'Adrenal Shot',
    FACTION.COMMON,
    SEASON.ONE,
    20,
    'When this model is activated you may discard this upgrade to move it by 2 hexes in any direction.',
    undefined,
    ['move','discard'],
  ),
  upgrade(
    'Heavy Armor',
    FACTION.COMMON,
    SEASON.ONE,
    20,
    'This model gets +2 health but -1 speed (down to a minimum of 1)',
    undefined,
    ['health','speed'],
  ),
  upgrade(
    'Medkit',
    FACTION.COMMON,
    SEASON.ONE,
    20,
    'When this model is activated you may discard this upgrade to remove 2 damage from it.',
    undefined,
    ['health','discard'],
  ),
  upgrade(
    'Living Ammo',
    FACTION.HIVES,
    SEASON.ONE,
    10,
    'This upgrade my only be equipped by Hive Warrior models. The first time this model makes a range 3 attack action each round, it may immediately make another free range 3 attack action.',
    undefined,
    ['attack','ranged'],
  ),
  upgrade(
    'Tough Skull',
    FACTION.HIVES,
    SEASON.ONE,
    10,
    'This model´s range 1 attacks gain the Knockback rule',
    undefined,
    ['melee'],
  ),
  upgrade(
    'Blood Lust',
    FACTION.HIVES,
    SEASON.ONE,
    10,
    'This model´s range 1 attacks gain the Cleave rule when targeting damaged models.',
    undefined,
    ['melee'],
  ),
  upgrade(
    'Hardened Carapace',
    FACTION.HIVES,
    SEASON.ONE,
    15,
    'Whenever this model takes any damage reduce the total by 1, to a minimum of 1.',
    undefined,
    ['health'],
  ),
  upgrade(
    'Dual Claws',
    FACTION.HIVES,
    SEASON.ONE,
    15,
    'Restricted: Assault Grunts. ',
    weapon('Dual Claws',1,3,4,[],'This weapon may only be equipped by Assault Grunts.'),
    ['melee'],
  ),
  upgrade(
    'Tail Pincer',
    FACTION.HIVES,
    SEASON.ONE,
    15,
    'Restricted: Soul-Snatchers.',
    weapon('Tail Pincer',1,2,2,[TRAITS.CLEAVE],'When landing a crit, this weapon gets +2 strength and +4 damage.'),
    ['melee','crit'],
  ),
  upgrade(
    'Adrenaline',
    FACTION.HIVES,
    SEASON.ONE,
    20,
    'This model gets +2 speed.',
    undefined,
    ['speed'],
  ),
  upgrade(
    'Terrifying Shriek',
    FACTION.HIVES,
    SEASON.ONE,
    20,
    'As an action, all adjacent enemy models are pushed away 1 hex and stop being on Guard.',
    undefined,
    ['aoe','action'],
  ),
  upgrade(
    'Hive Protection',
    FACTION.HIVES,
    SEASON.ONE,
    20,
    'When attacked by damaged enemy models, this model ignore crit effects and gets +1 defence.',
    undefined,
    ['defence'],
  ),
  upgrade(
    'Power Charge',
    FACTION.MARAUDERS,
    SEASON.ONE,
    10,
    'When this model makes a charge action it´s range 1 weapons get the Cleave special rule.',
    undefined,
    ['melee'],
  ),
  upgrade(
    'Cocky',
    FACTION.MARAUDERS,
    SEASON.ONE,
    10,
    'When this model gets +1 strength with range 1 weapons when attacking enemy heroes.',
    undefined,
    ['melee'],
  ),
  upgrade(
    'Unmovable',
    FACTION.MARAUDERS,
    SEASON.ONE,
    10,
    'This model can only be pushed if the enemy lands a crit.',
    undefined,
    ['defence'],
  ),
  upgrade(
    'Eager',
    FACTION.MARAUDERS,
    SEASON.ONE,
    15,
    'This model´s range 1 weapons get +1 strength when charging.',
    undefined,
    ['melee','charge'],
  ),
  upgrade(
    'Brutal Swing',
    FACTION.MARAUDERS,
    SEASON.ONE,
    15,
    undefined,
    weapon('Brutal Swing',1,3,4,['Burst'], ''),
    ['weapon','melee','aoe'],
  ),
  upgrade(
    'Headbutt',
    FACTION.MARAUDERS,
    SEASON.ONE,
    15,
    undefined,
    weapon('Headbutt',1,3,4,[], 'When attacking roll one die, on a 5-6 the target model can´t be activated again this round.'),
    ['weapon','melee'],
  ),
  upgrade(
    'Crushing Grip',
    FACTION.MARAUDERS,
    SEASON.ONE,
    20,
    'This model´s range 1 weapons get the Cleave special rule',
    undefined,
    ['melee'],
  ),
  upgrade(
    'Cyborg Body',
    FACTION.MARAUDERS,
    SEASON.ONE,
    20,
    'Whenever this model takes any damage reduce the damage by 1, to a minimum of 1.',
    undefined,
    ['health'],
  ),
  upgrade(
    'Unkillable',
    FACTION.MARAUDERS,
    SEASON.ONE,
    20,
    'If this model would be killed roll one die, on a 5-6 the model takes no damage and this upgrade is discarded.',
    undefined,
    ['health'],
  ),
  upgrade(
    'God-King´s Might',
    FACTION.BROTHERS,
    SEASON.ONE,
    10,
    'The model´s range 1 weapons get the Cleave special rule.',
    undefined,
    ['melee'],
  ),
  upgrade(
    'Push Back',
    FACTION.BROTHERS,
    SEASON.ONE,
    10,
    'If the model is grazed by an adjacent enemy, then it may push the attacking model by 1 hex.',
    undefined,
    ['melee','defence'],
  ),
  upgrade(
    'Shock Grenades',
    FACTION.BROTHERS,
    SEASON.ONE,
    10,
    'If this model lands a crit when attacking with a range 1 weapon, then all enemies adjacent to the target take 1 damage.',
    undefined,
    ['melee','aoe'],
  ),
  upgrade(
    'Coordinated Defense',
    FACTION.BROTHERS,
    SEASON.ONE,
    15,
    'As an action this model and all adjacent friendly models may be put on Guard.',
    undefined,
    ['guard','aoe'],
  ),
  upgrade(
    'Heroic Strike',
    FACTION.BROTHERS,
    SEASON.ONE,
    15,
    undefined,
    weapon('Heroic Strike',1,2,4,[],'This attack gets +2 strength if no friendly models are adjacent.'),
    ['weapon','melee'],
  ),
  upgrade(
    'Chainsaw Sword',
    FACTION.BROTHERS,
    SEASON.ONE,
    15,
    undefined,
    weapon('Chainsaw Sword',1,2,3,[],'This weapon deals +3 damage when landing crits.'),
    ['weapon','melee'],
  ),
  upgrade(
    'Aggressive',
    FACTION.BROTHERS,
    SEASON.ONE,
    20,
    'If an enemy model ends its move within 2 hexes of this model, then this model may move by 1 hex, as long as it ends up closer to that enemy model.',
    undefined,
    ['move'],
  ),
  upgrade(
    'Blessed Halo',
    FACTION.BROTHERS,
    SEASON.ONE,
    20,
    'This model gets +2 Health.',
    undefined,
    ['health'],
  ),
  upgrade(
    'Cleansing Blow',
    FACTION.BROTHERS,
    SEASON.ONE,
    20,
    undefined,
    weapon('Cleansing Blow',1,3,4,[],'If the attack targets an enemy hero, then the model may make attack the same target twice.'),
    ['weapon','melee'],
  ),
];

const factions = [
  FACTION.COMMON,
  FACTION.HIVES,
  FACTION.BROTHERS,
  FACTION.MARAUDERS,
];

module.exports = {
  factions,
  upgradeCards,
};
